apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-application
spec:
  selector:
    matchLabels:
      app: rag-application
  replicas: 1
  template:
    metadata:
      labels:
        app: rag-application
    spec:
      containers:
      - name: rag-application
        image: reet02/rag-application:8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Adding health checks (customize the path and port as needed)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-application-service  
spec:
  selector:
    app: rag-application
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
